apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: brcomstoazchcaptureorder 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: brcomstoazchcaptureorder 
    spec:
      containers:
        - name: brcomstoazchcaptureorder 
          image: brantreg.azurecr.io/brcomstoazchcaptureorder 
          ports:
          - containerPort: 8080